from electro_modelling.models.networks.dcgan_generator import DCGANGenerator
from electro_modelling.models.networks.dcgan_discriminator import DCGANDiscriminator
from electro_modelling.models.networks.gansynth_generator import GANSynthGenerator
from electro_modelling.models.networks.gansynth_discriminator import GANSynthDiscriminator
